apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1
  selector:
    # busca todos os pods com a label 'app: event-bus', isso informa qual pod deve ser gerenciado pelo deployment
    matchLabels:
      app: event-bus
  template: # especifica as configurações de um pod
    metadata:
      labels: # queremos que um pod tenha a label 'app: event-bus'
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: alxrdev/event-bus
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
spec:
  type: ClusterIP
  selector:
    app: event-bus
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005