apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-depl
spec:
  replicas: 1
  selector:
    # busca todos os pods com a label 'app: moderation', isso informa qual pod deve ser gerenciado pelo deployment
    matchLabels:
      app: moderation
  template: # especifica as configurações de um pod
    metadata:
      labels: # queremos que um pod tenha a label 'app: moderation'
        app: moderation
    spec:
      containers:
        - name: moderation
          image: alxrdev/moderation
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-srv
spec:
  type: ClusterIP
  selector:
    app: moderation
  ports:
    - name: moderation
      protocol: TCP
      port: 4003
      targetPort: 4003